version: "3.9"

services:
  backend:
    build: ./server
    env_file: 
      - ./server/.env
    ports:
      - "3000:3000"
    networks:
      - smartkit_network
    depends_on:
      - mongodb

  frontend:
    build: ./client
    env_file: 
      - ./client/.env
    ports:
      - "5173:5173"
    networks:
      - smartkit_network
      

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - smartkit_network
    volumes:
      - smartkit-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  smartkit_network:
    driver: bridge

volumes:
  smartkit-data:
    driver: local
